apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: default
type: Opaque
stringData:
  user-uri: mongodb+srv://durganaresh:Naresh4130@durga-cluster.htudsah.mongodb.net/ecommerce-store
  product-uri: mongodb+srv://durganaresh:Naresh4130@durga-cluster.htudsah.mongodb.net/ecommerce-products
  cart-uri: mongodb+srv://durganaresh:Naresh4130@durga-cluster.htudsah.mongodb.net/ecommerce-carts
  order-uri: mongodb+srv://durganaresh:Naresh4130@durga-cluster.htudsah.mongodb.net/ecommerce-orders
