apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: default
type: Opaque
stringData:
  # Replace with your MongoDB Atlas connection strings
  # Format: mongodb+srv://username:password@cluster.region.mongodb.net/database-name
  user-uri: mongodb+srv://USERNAME:PASSWORD@cluster.region.mongodb.net/ecommerce-store
  product-uri: mongodb+srv://USERNAME:PASSWORD@cluster.region.mongodb.net/ecommerce-products
  cart-uri: mongodb+srv://USERNAME:PASSWORD@cluster.region.mongodb.net/ecommerce-carts
  order-uri: mongodb+srv://USERNAME:PASSWORD@cluster.region.mongodb.net/ecommerce-orders
